export const sentenceAchievement = [
    {
        title: "duelA1.title",
        achievements: [
            {
                id: 'a1_wins_1',
                name: 'duelA1.firstWinName',
                description: 'duelA1.firstWinDescription',
                icon: '🏆',
                currentProgress: 0,
                targetProgress: 1,
            },
            {
                id: 'a1_wins_10',
                name: 'duelA1.secondWinName',
                description: 'duelA1.secondWinDescription',
                icon: '🥈',
                currentProgress: 0,
                targetProgress: 10,
            },
            {
                id: 'a1_streaks_3',
                name: 'duelA1.streak3Name',
                description: 'duelA1.streak3Description',
                icon: '⚔️',
                currentProgress: 0,
                targetProgress: 3,
            },
            {
                id: 'a1_streaks_10',
                name: 'duelA1.streak10Name',
                description: 'duelA1.streak10Description',
                icon: '🐺',
                currentProgress: 0,
                targetProgress: 10,
            },
            {
                id: 'a1_cleanSweeps_5',
                name: 'duelA1.cleanSweeps5',
                description: 'duelA1.cleanSweeps5Description',
                icon: '🌟',
                currentProgress: 0,
                targetProgress: 20,
            },
        ]
    },
    {
        title: "duelA2.title",
        achievements: [
            {
                id: 'a2_wins_1',
                name: 'duelA2.firstWinName',
                description: 'duelA2.firstWinDescription',
                icon: '🥇',
                currentProgress: 0,
                targetProgress: 1,
            },
            {
                id: 'a2_wins_5',
                name: 'duelA2.secondWinName',
                description: 'duelA2.secondWinDescription',
                icon: '🥉',
                currentProgress: 0,
                targetProgress: 10,
            },
            {
                id: 'a2_streaks_5',
                name: 'duelA2.streak5Name',
                description: 'duelA2.streak5Description',
                icon: '🦅',
                currentProgress: 0,
                targetProgress: 5,
            },
            {
                id: 'a2_streaks_10',
                name: 'duelA2.streak10Name',
                description: 'duelA2.streak10Description',
                icon: '⚡',
                currentProgress: 0,
                targetProgress: 10,
            },
            {
                id: 'a2_cleanSweeps_20',
                name: 'duelA2.cleanSweeps20',
                description: 'duelA2.cleanSweeps20Description',
                icon: '🎯',
                currentProgress: 0,
                targetProgress: 20,
            },
        ]
    },
    {
        title: "duelB1.title",
        achievements: [
            {
                id: 'b1_wins_1',
                name: 'duelB1.firstWinName',
                description: 'duelB1.firstWinDescription',
                icon: '🥏',
                currentProgress: 0,
                targetProgress: 1,
            },
            {
                id: 'b1_wins_10',
                name: 'duelB1.secondWinName',
                description: 'duelB1.secondWinDescription',
                icon: '🎖️',
                currentProgress: 0,
                targetProgress: 10,
            },
            {
                id: 'b1_streaks_5',
                name: 'duelB1.streak5Name',
                description: 'duelB1.streak5Description',
                icon: '🦁',
                currentProgress: 0,
                targetProgress: 5,
            },
            {
                id: 'b1_streaks_10',
                name: 'duelB1.streak10Name',
                description: 'duelB1.streak10Description',
                icon: '🔥',
                currentProgress: 0,
                targetProgress: 10,
            },
            {
                id: 'b1_cleanSweeps_20',
                name: 'duelB1.cleanSweeps20',
                description: 'duelB1.cleanSweeps20Description',
                icon: '💎',
                currentProgress: 0,
                targetProgress: 20,
            },
        ]
    },
    {
        title: "duelB2.title",
        achievements: [
            {
                id: 'b2_wins_1',
                name: 'duelB2.firstWinName',
                description: 'duelB2.firstWinDescription',
                icon: '🛡️',
                currentProgress: 0,
                targetProgress: 1,
            },
            {
                id: 'b2_wins_20',
                name: 'duelB2.secondWinName',
                description: 'duelB2.secondWinDescription',
                icon: '🐉',
                currentProgress: 0,
                targetProgress: 20,
            },
            {
                id: 'b2_streaks_5',
                name: 'duelB2.streak5Name',
                description: 'duelB2.streak5Description',
                icon: '👑',
                currentProgress: 0,
                targetProgress: 5,
            },
            {
                id: 'b2_streaks_10',
                name: 'duelB2.streak10Name',
                description: 'duelB2.streak10Description',
                icon: '🌌',
                currentProgress: 0,
                targetProgress: 10,
            },
            {
                id: 'b2_cleanSweeps_10',
                name: 'duelB2.cleanSweeps20',
                description: 'duelB2.cleanSweeps20Description',
                icon: '⭐',
                currentProgress: 0,
                targetProgress: 10,
            },
        ]
    }
];
