export const nameMap = {
    Furniture: 'nameMap.Furniture',
    Animals: 'nameMap.Animals',
    Birds: 'Птицы',
    SeaAnimals: 'Морские животные',
    Insects: 'Насекомые',
    Savanna: 'Саванна',
    Clothes: 'nameMap.Clothes',
    Shoes: 'Обувь',
    Food: 'nameMap.Food',
    SweetEat: 'Сладости',
    MilkEat: 'Молочные продукты',
    Vegetables: 'Овощи',
    Fruits: 'Фрукты',
    Drinks: 'Напитки',
    Body: 'nameMap.Body',
    Professions: 'nameMap.Professions',
    Transport: 'nameMap.Transport',
    Colors: 'nameMap.Colors',
    Nature: 'nameMap.Nature',
    Weather: 'Погода',
    Landscape: 'Ландшафт',
    Home: 'nameMap.Home',
    Zeit: 'nameMap.Zeit',
    CityBuildings: 'Здания',
    CityInfrastructure: 'Инфроструктура',
    School: 'nameMap.School',
    DaysAndMonths: 'nameMap.DaysAndMonths',
    Toys: 'nameMap.Toys',
    CommonItems: 'nameMap.CommonItems',
    BathroomItems: 'nameMap.BathroomItems',
    Kosmetik: 'nameMap.Kosmetik',
    Familie: 'nameMap.Familie',
    Emotions: 'nameMap.Emotions',
    Kitchen: 'nameMap.Kitchen',
    Health: 'nameMap.Health',
    SportBasic: 'Виды спорта',
    SportCombatWinter: 'Зимний спорт и борьба',
    SportEvents: 'Турниры и награды',
    SportLife: 'Тренировки',
    SportEquipment: 'Спортинвентарь',
    TravelDocuments: 'Документы',
    Tourism: 'Туризм',
    Travel: 'nameMap.Travel',
    MusicInstruments: 'Музыкальные инструменты',
    Musik: 'nameMap.Musik',
    Amount: 'nameMap.Amount',
    Hardware: 'Орорудования',
    Software: 'Программы',
    Internet: 'Интернет',
    WinterHolidays: 'Зимние',
    FamilyAndReligious: 'Семейные',
    PersonalCelebrations: 'Торжества',
    FestivalsAndDecor: 'Фестивали',
    DwellingTypes: 'Жилье',
    Rooms: 'Комнаты',
    ConstructionAndDetails: 'Детали',
    CoreFamily: 'Близкие',
    ExtendedFamily: 'Родственники',
    Relationships: 'Пара и свояки',
    HandTools: 'Ручной',
    PowerTools: 'Электро',
    ConsumablesAndSafety: 'Материал',
    JobOffice: 'Бизнес',
    JobTech: 'Инженерное',
    JobMed: 'Медицина',
    JobEdu: 'Обучение',
    JobService: 'Услуги',
    CityTransport: 'Транспорт',
    TravelTransport: 'Транспорт'
}

export  const nameMode = {
    wordTranslate: 'modes.wordTranslate',
    article: 'modes.article',
    letters: 'modes.letters',
    wordArticle: 'modes.articleWord',
    plural: 'modes.plural',
    audio: 'modes.audio'
}

