
export const nameMap = {
    Furniture: 'nameMap.Furniture',
    Animals: 'nameMap.Animals',
    Birds: 'nameMap.Birds',
    SeaAnimals: 'nameMap.SeaAnimals',
    Insects: 'nameMap.Insects',
    Savanna: 'nameMap.Savanna',
    Clothes: 'nameMap.Clothes',
    Shoes: 'nameMap.Shoes',
    Food: 'nameMap.Food',
    SweetEat: 'nameMap.SweetEat',
    MilkEat: 'nameMap.MilkEat',
    Vegetables: 'nameMap.Vegetables',
    Fruits: 'nameMap.Fruits',
    Drinks: 'nameMap.Drinks',
    Body: 'nameMap.Body',
    Professions: 'nameMap.Professions',
    Transport: 'nameMap.Transport',
    Colors: 'nameMap.Colors',
    Nature: 'nameMap.Nature',
    Weather: 'nameMap.Weather',
    Landscape: 'nameMap.Landscape',
    Home: 'nameMap.Home',
    Zeit: 'nameMap.Zeit',
    CityBuildings: 'nameMap.CityBuildings',
    CityInfrastructure: 'nameMap.CityInfrastructure',
    School: 'nameMap.School',
    DaysAndMonths: 'nameMap.DaysAndMonths',
    Toys: 'nameMap.Toys',
    CommonItems: 'nameMap.CommonItems',
    BathroomItems: 'nameMap.BathroomItems',
    Kosmetik: 'nameMap.Kosmetik',
    Familie: 'nameMap.Familie',
    Emotions: 'nameMap.Emotions',
    Kitchen: 'nameMap.Kitchen',
    Health: 'nameMap.Health',
    SportBasic: 'nameMap.SportBasic',
    SportCombatWinter: 'nameMap.SportCombatWinter',
    SportEvents: 'nameMap.SportEvents',
    SportLife: 'nameMap.SportLife',
    SportEquipment: 'nameMap.SportEquipment',
    TravelDocuments: 'nameMap.TravelDocuments',
    Tourism: 'nameMap.Tourism',
    Travel: 'nameMap.Travel',
    MusicInstruments: 'nameMap.MusicInstruments',
    Musik: 'nameMap.Musik',
    Amount: 'nameMap.Amount',
    Hardware: 'nameMap.Hardware',
    Software: 'nameMap.Software',
    Internet: 'nameMap.Internet',
    WinterHolidays: 'nameMap.WinterHolidays',
    FamilyAndReligious: 'nameMap.FamilyAndReligious',
    PersonalCelebrations: 'nameMap.PersonalCelebrations',
    FestivalsAndDecor: 'nameMap.FestivalsAndDecor',
    DwellingTypes: 'nameMap.DwellingTypes',
    Rooms: 'nameMap.Rooms',
    ConstructionAndDetails: 'nameMap.ConstructionAndDetails',
    CoreFamily: 'nameMap.CoreFamily',
    ExtendedFamily: 'nameMap.ExtendedFamily',
    Relationships: 'nameMap.Relationships',
    HandTools: 'nameMap.HandTools',
    PowerTools: 'nameMap.PowerTools',
    ConsumablesAndSafety: 'nameMap.ConsumablesAndSafety',
    JobOffice: 'nameMap.JobOffice',
    JobTech: 'nameMap.JobTech',
    JobMed: 'nameMap.JobMed',
    JobEdu: 'nameMap.JobEdu',
    JobService: 'nameMap.JobService',
    CityTransport: 'nameMap.CityTransport',
    TravelTransport: 'nameMap.TravelTransport',
    usualClothes: 'nameMap.usualClothes',
    winterClothes: 'nameMap.winterClothes',
    positiveEmotions: 'nameMap.emotionsPositive',
    negativeEmotions: 'nameMap.emotionsNegative'
}

export const categories = [
    {id: 'nature', title: 'categoryWords.nature', topics: ['Nature', 'Weather', 'Landscape']},
    {id: 'animals', title: 'categoryWords.animals', topics: ['Animals', 'Birds', 'SeaAnimals', 'Insects', 'Savanna']},
    {id: 'food', title: 'categoryWords.food', topics: ['Food', 'MilkEat', 'SweetEat', 'Vegetables', 'Fruits', 'Drinks']},
    {id: 'people', title: 'categoryWords.people', topics: ['Body',  'positiveEmotions', 'negativeEmotions']},
    {id: 'family', title: 'categoryWords.family', topics: ['CoreFamily', 'ExtendedFamily', 'Relationships', 'StepAndInLaws']},
    {id: 'dailyRoutine', title: 'categoryWords.dailyRoutine', topics: [ 'Kitchen', 'BathroomItems', 'Kosmetik', 'CommonItems', 'Toys']},
    {id: 'house', title: 'categoryWords.house', topics: ['DwellingTypes', 'Rooms', 'ConstructionAndDetails']},
    {id: 'city', title: 'categoryWords.city', topics: ['CityInfrastructure', 'CityBuildings', 'CityTransport']},
    {id: 'school', title: 'categoryWords.school', topics: ['School', 'Colors']},
    {id: 'work', title: 'categoryWords.professions', topics: ['JobOffice', 'JobTech', 'JobMed', 'JobEdu', 'JobService' ]},
    {id: 'building', title: 'categoryWords.construction', topics: ['HandTools', 'PowerTools', 'ConsumablesAndSafety']},
    {id: 'lifestyle', title: 'categoryWords.clothes', topics: ['usualClothes', 'winterClothes', 'Shoes', 'Clothes']},
    {id: 'holidays', title: 'categoryWords.holidays', topics: ['WinterHolidays', 'FamilyAndReligious', 'PersonalCelebrations', 'FestivalsAndDecor']},
    {id: 'sport', title: 'categoryWords.sport', topics: ['SportBasic', 'SportCombatWinter', 'SportEvents', 'SportLife', 'SportEquipment']},
    {id: 'music', title: 'categoryWords.music', topics: ['Musik', 'MusicInstruments']},
    {id: 'travel', title: 'categoryWords.travel', topics: ['Travel', 'TravelDocuments', 'Tourism', 'TravelTransport']},
    {id: 'informatics', title: 'categoryWords.informatics', topics: ['Hardware', 'Software', 'Internet']},
    {id: 'abstract', title: 'categoryWords.abstract', topics: ['Zeit', 'DaysAndMonths', 'Amount']}
]

export const nameMode = {
    wordTranslate: 'modes.wordTranslate',
    article: 'modes.article',
    letters: 'modes.letters',
    wordArticle: 'modes.articleWord',
    plural: 'modes.plural',
    audio: 'modes.audio'
}

export const iconMap = {
    Furniture: '🪑', Animals: '🦁', Birds: '🦅', SeaAnimals: '🐬',
    Insects: '🦋', Savanna: '🦒', Clothes: '👕', Shoes: '👟',
    Food: '🍔', MilkEat: '🥛', SweetEat: '🍬', Vegetables: '🥦',
    Fruits: '🍎', Drinks: '🥤', Body: '🦵', Professions: '💼',
    Colors: '🎨', Nature: '🌲', Weather: '🌤️',
    Landscape: '🏔️', Home: '🏠', Zeit: '⏳', CityInfrastructure: '🛣️',
    CityBuildings: '🏢', School: '🏫', DaysAndMonths: '📅',
    Toys: '🧸', CommonItems: '📦', BathroomItems: '🛁',
    Kosmetik: '💄', Familie: '👨‍👩‍👧‍👦', Werkzeuge: '🛠️',
    Kitchen: '🍳', Health: '⚕️', SportBasic: '⚽', SportEquipment: '🏋️',
    SportCombatWinter: '🏂', SportEvents: '🏅', SportLife: '🏃',
    TravelDocuments: '🛂', Tourism: '🗺️', Travel: '🧳',
    MusicInstruments: '🎸', Musik: '🎵', Amount: '🔢',
    Hardware: '🖥️', Software: '💻', Internet: '🌐',
    WinterHolidays: '🎄', FamilyAndReligious: '🕊️',
    PersonalCelebrations: '🎂', FestivalsAndDecor: '🎉',
    DwellingTypes: '🛖', Rooms: '🚪',
    ConstructionAndDetails: '🧱', CoreFamily: '👪',
    Relationships: '🤝', ExtendedFamily: '👴',
    HandTools: '🪛', PowerTools: '🪚',
    ConsumablesAndSafety: '🦺', JobOffice: '🏢',
    JobTech: '⚙️', JobMed: '🩺', JobEdu: '🎓',
    JobService: '🛎️', CityTransport: '🚌',
    TravelTransport: '✈️', usualClothes: '👕',
    winterClothes: '🧥',
    positiveEmotions: '😀',
    negativeEmotions: '😔'
}

export const topicColors = ['#FFEB7F', '#9DFFBB', '#FFAFF3', '#88B5FF', '#FF9F7F', '#AFAFFF', '#7FFFDF', '#FFD1AF']

export const baseModes = [
    {key: 'wordTranslate', label: 'modes.wordTranslate'},
    {key: 'article', label: 'modes.article'},
    {key: 'letters', label: 'modes.letters'},
    {key: 'wordArticle', label: 'modes.articleWord'},
    {key: 'plural', label: 'modes.plural'},
    {key: 'audio', label: 'modes.audio'}
]
